os: linux
dist: trusty
language: go

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - tip

script:
  - go get ./...
  - gofmt -d -s .
  - go vet *.go
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  bash <(curl -s https://codecov.io/bash)